### ISSUE TITLE
你好，寻求帮助😂Hi, can I help you? ??

### ISSUE THREAD

**Issue by fwz233** [ITAxReal/itaxreal.github.io#1]
我也做了一个第三方应用的网站，但是可能最近会关闭，可以把那里面几本小说添加到你这个网站吗？
I also made a third-party application site, but may be closed recently, can you add a few novels to your site?
我的网站是My Web site is http://zeppos.store
这种小说软件的源码是The source code for this novel software is:https://github.com/fwz233/txtview
5个程序的appid是1001001到1001005
The appid for the five programs is 1001001 to 1001005
——————————————————
顺便我很好奇这种链接是怎么找到的😂是用抓包软件提取的吗By the way I am curious how this link is found? 😂?is it extracted with the capture software
like this:
zpkd1://store-cdn.huami.com/custom_user_app/20220829/hwZOyrMISceXxsOoorsTJQGBBrEOUGQk/gtr3-pro.zip

**Comment by ITAxReal** [comment]
Hello. I can add your applications, but you should give me a link to zipped application hosted on Amazfit/Zepp services.
This links were extracted from official Zepp repository.
